### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by pyrschool** [ozcankursun/e-shop-front-end#2]
Every site has a landing page, a default page, the page you see when you ask for no specific page. When you go to https://pyrschool.github.io/ReservationsDemo/ you are not asking for a particular page so the server serves the landing page. By tradition, the landing page is index.html. So when you ask for nothing, the server tries to give you index.html.

You should move your index.html to the root and not inside Pages. THere are other approaches but for now let's stick to the simple rule: each site should have an index.html.

**Comment by ozcankursun** [comment]
Should I move only index.html or all the pages
