### ISSUE TITLE
Navbar for owner pages

### ISSUE THREAD

**Issue by pyrschool** [ozcankursun/e-shop-front-end#3]
At https://docs.google.com/document/d/123uTGiJ5JzbIBKNc-EVMlqK1LHxYdZEeYSAcsom-5lM/edit#heading=h.kh7ocrdcjpl3 -> 4 it says that CRUD (aka owner) pages should have a menu that allows to go to the other CRUD pages, so the menu shgould havethese entries: Manufactuirers, Order, Cloths.

**Comment by ozcankursun** [comment]
done
